display_name: FaForever
package_name: faforever
maintainer:
  name: kjxbyz
  email: kjxbyz888@outlook.com
priority: optional
section: x11
installed_size: 6604
essential: false
icon: logo/logo-512.png
metainfo: linux/shared/faforever.metainfo.xml

postinstall_scripts:
  - echo "Installing FaForever"
postuninstall_scripts:
  - echo "FaForever installed"

keywords:
  - FaForever
  - Music

generic_name: FaForever

categories:
  - Audio

startup_notify: true
